version: "3.8"

services:
  postgres_db:
    image: postgres:latest
    container_name: postgres
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres123
      - POSTGRES_DB=coachnpdb
    ports:
      - "5432:5432"
    volumes:
      - ./database:/var/lib/postgresql/data
