name: Deploy

on:
  push:
    branches:
      - deploy

jobs:
  build:
    name: Deploy to server
    runs-on: ubuntu-latest
    steps:
      - name: executing remote ssh commands using ssh key
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          script: |
            cd /home/ubuntu/apps/coach-backend-sl
            git pull
            sudo docker build -t coach-backend-sl .
            sudo docker-compose up -d
