name: Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Deploy to server
    strategy:
      matrix:
        node-version: [16.x]
    runs-on: ubuntu-latest
    steps:
      - name: executing remote ssh commands using ssh key
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          script: |
            cd containers/coach-backend-sl
            git pull
            sudo docker build -t coach-backend-sl .
            sudo docker-compose up -d
